runtime: php72

handlers:
- url: /(.+\.(gif|png|jpg|html))$
  static_files: \1
  upload: .+\.(gif|png|jpg|html)$

- url: /asciirocks/images
  static_dir: images

- url: /asciirocks/css     
  static_dir: css

- url: /asciirocks/scripts
  static_dir: scripts

- url: /asciirocks/fileuploader
  static_dir: fileuploader 

- url: /asciirocks/ans
  static_dir: ans

- url: /(.+\.php)$
  script: auto

- url: /asciirocks/(.+\.php)$
  script: auto
