runtime: php72

handlers:

- url: /asciirocks/images
  static_dir: asciirocks/images

- url: /asciirocks/css     
  static_dir: asciirocks/css

- url: /asciirocks/scripts
  static_dir: asciirocks/scripts

- url: /asciirocks/fileuploader
  static_dir: asciirocks/fileuploader 

- url: /asciirocks/ans
  static_dir: asciirocks/ans

- url: /(.+\.php)$
  script: auto

