runtime: php72

handlers:

- url: /asciirocks/assets
  static_dir: asciirocks/assets

- url: /asciirocks/images
  static_dir: asciirocks/images

- url: /asciirocks/css     
  static_dir: asciirocks/css

- url: /asciirocks/scripts
  static_dir: asciirocks/scripts

- url: /asciirocks/fileuploader
  static_dir: asciirocks/fileuploader 

- url: /asciirocks/ans
  static_dir: asciirocks/ans

- url: /asciiss/asciirocks/scripts
  static_dir: asciiss/asciirocks/scripts

- url: /asciiss/asciirocks/css
  static_dir: asciiss/asciirocks/css

- url: /asciiss/asciirocks/images
  static_dir: asciiss/asciirocks/images

- url: /asciiss/scripts
  static_dir: asciiss/scripts

- url: /asciinibbles/scripts
  static_dir: asciinibbles/scripts

- url: /asciinibbles/asciirocks/scripts
  static_dir: asciinibbles/asciirocks/scripts

- url: /asciinibbles/asciiss/scripts
  static_dir: asciinibbles/asciiss/scripts

- url: /asciinibbles/asciirocks/css
  static_dir: asciinibbles/asciirocks/css

- url: /(.+\.php)$
  script: auto

